# Generated by Django 4.0.3 on 2022-05-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_num',
            field=models.IntegerField(default=1),
        ),
    ]
