# Generated by Django 4.0.3 on 2022-05-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_room_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_num',
            field=models.IntegerField(),
        ),
    ]
