# Generated by Django 4.0.3 on 2022-05-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_no_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
