# Generated by Django 4.0.3 on 2022-05-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
    ]
