# Generated by Django 4.0.3 on 2022-05-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_payment_booking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='booking_code',
            field=models.CharField(max_length=50),
        ),
    ]
