# Generated by Django 4.0.3 on 2022-05-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_payment_booking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_note',
            field=models.TextField(blank=True, default='a', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='admin_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
