# Generated by Django 4.0.3 on 2022-05-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_payment_admin_note_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
